networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v2.24.23@sha256:eca68fc4cd6e2045bf56bd42c7410b51a528cebc487e554c0da08f32c7842de8
    labels:
      traefik.enable: true
      traefik.http.middlewares.university-notes-cors.headers.accesscontrolalloworiginlist: https://metrics.zarantonello.dev
      traefik.http.routers.university-notes.entrypoints: cloudflare
      traefik.http.routers.university-notes.middlewares: university-notes-cors
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
