networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v2.24.15@sha256:386508166ab79b851fda9e9217d735c1916662c0225c1e18ff54886759e79181
    labels:
      traefik.enable: true
      traefik.http.middlewares.university-notes-cors.headers.accesscontrolalloworiginlist: https://metrics.zarantonello.dev
      traefik.http.routers.university-notes.entrypoints: cloudflare
      traefik.http.routers.university-notes.middlewares: university-notes-cors
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
