concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci-yamllint:latest@sha256:3fd6ee76309b026e8dfd49f7fe6dc99d6f761184d93a0de2f6c0a51d0c2b1349
    name: Lint yaml files
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run yamllint
        run: yamllint .

name: check-yamllint.yaml

"on":
  pull_request:
    branches:
      - main
