concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes:ci@sha256:49c514a54ac20f068721f375dc60cb2d40076b069736fc2881459cd15c5855ae
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Check that project builds
    runs-on: srv-home
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Build the website
        run: pnpm run build
      # Can only be done after the site has been built.
      - name: Check for latex rendering errors
        run: sh -c '! grep cc0000 dist/ -rl'

name: check-build.yaml

"on":
  pull_request:
    branches:
      - main
