concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes-ci:v2026.09.23.2@sha256:c1a077e1cdb8c2e75a650332128345a3c15a4c39620e870c5b194c427a16b674
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Check that project builds
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Build the website
        run: pnpm run build

name: check-build.yaml

"on":
  pull_request:
    branches:
      - main
