concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci-commitizen:v1.0.5@sha256:a0eb92d26661487813e5176d460bf68ce4b9c92a0f98cdc30c13bd9c3f84d9f0
    name: Check the PR title
    runs-on: srv-generic
    steps:
      - name: Run commitizen
        run: cz check --message '${{ forge.event.pull_request.title }}'

name: check-commitizen.yaml

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
