concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes:ci@sha256:3cd5fcc80e813393ab26114b9bc001dc09e65ba84b61eab9a1b53e25d90921f1
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with formatters
    runs-on: srv-0-thi-home
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run formatter
        run: pnpm run format:check

name: check-formatter.yaml

"on":
  pull_request:
    branches:
      - main
