concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes:ci@sha256:ac6994e22a2d524001fada4b54dbce7335f389f416f0d07cb4f1bf76ab14176d
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with static tools
    runs-on: srv-0-thi-home
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run types and syntax check
        run: pnpm run check

name: check-syntax.yaml

"on":
  pull_request:
    branches:
      - main
