concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v3.0.4@sha256:2b74d31e6187f85a371817f8e32db14ee9105bdfd398cd2788734cb0883be9d6
    name: Lint yaml files
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run yamllint
        run: yamllint .

name: check-yamllint.yaml

"on":
  pull_request:
    branches:
      - main
