concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:v3.0.3@sha256:2b74d31e6187f85a371817f8e32db14ee9105bdfd398cd2788734cb0883be9d6
    name: Checks
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Restore the pnpm cache
        uses: https://data.forgejo.org/actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ${{ forge.workspace }}/.pnpm-store
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run formatter
        run: pnpm run format:check
      - name: Run linter
        run: pnpm run lint:check
      - name: Run types and syntax check
        run: pnpm run check
      - name: Build the website
        run: pnpm run build
      - name: Check for latex rendering errors
        run: sh -c '! grep cc0000 dist/ -rl'

name: check.yaml

"on":
  pull_request:
    branches:
      - main
