concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v3.0.4@sha256:8782bc8c051eb919897ac94199e68f6daa0721082f46ca16ecb0514aa4c53af9
    name: Lint yaml files
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run yamllint
        run: yamllint .

name: check-yamllint.yaml

"on":
  pull_request:
    branches:
      - main
