concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes:ci@sha256:f50a97525c08297d9b94c16faf61b27a6324f8b3d58a934eb6e0f5508c55cbc7
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with static tools
    runs-on: srv-0-thi-home
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run types and syntax check
        run: pnpm run check

name: check-syntax.yaml

"on":
  pull_request:
    branches:
      - main
