concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes-ci:v2026.09.03.1@sha256:8e31ad0df2542b572ed883a8cda78baacf71fd294a1d6201641b5195a798d636
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with static tools
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run types and syntax check
        run: pnpm run check

name: check-syntax.yaml

"on":
  pull_request:
    branches:
      - main
