concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci:v3.0.4@sha256:2b74d31e6187f85a371817f8e32db14ee9105bdfd398cd2788734cb0883be9d6
      volumes:
        - forgejo-runner-cache-pnpm:/cache
    name: Checks
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Restore the pnpm cache
        run: if [ -d /cache/.pnpm-store ] ; then cp -r /cache/.pnpm-store/ . ; fi
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run formatter
        run: pnpm run format:check
      - name: Run linter
        run: pnpm run lint:check
      - name: Run types and syntax check
        run: pnpm run check
      - name: Build the website
        run: pnpm run build
      - name: Check for latex rendering errors
        run: sh -c '! grep cc0000 dist/ -rl'
      - if: always()
        name: Save the pnpm cache
        run: |
          rm -rf /cache/.pnpm-store/
          cp -r .pnpm-store/ /cache/

name: check.yaml

"on":
  pull_request:
    branches:
      - main
