concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/university/notes:ci@sha256:7f210aded35cccf638dc44d11d65c3a3491f6f1030f996ffe23e10a684bdfdfd
      volumes:
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: Checks with linters
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Run linter
        run: pnpm run lint:check

name: check-linter.yaml

"on":
  pull_request:
    branches:
      - main
