jobs:
  respond:
    container:
      image: git.zarantonello.dev/university/notes-ci:v2026.09.19.1@sha256:4d4cedbd3fac15ff65228b2cfbff81577a42166c561edf5573dee61cdd84e97e
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-pnpm:/usr/local/pnpm/store
    name: LLM Bot response generation
    runs-on: srv-generic
    steps:
      - name: Configure pi
        run: |
          mkdir -p ~/.pi/agent/

          cat << 'EOF' > ~/.pi/agent/auth.json
          ${{ secrets.PI_AUTH_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/models.json
          ${{ vars.PI_MODELS_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/settings.json
          ${{ vars.PI_SETTINGS_JSON }}
          EOF
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@14d91db19b461745538001cc5a0ed176ef018aec # v1.11.3
        with:
          auth-token: ${{ secrets.CI_BOT_TOKEN }}
          auth-username: ci-bot
          git-author: CI [bot]
          git-email: ci-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
