concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  release:
    container:
      image: git.zarantonello.dev/infra/ci-semantic-release:v1.0.3@sha256:d2f54e0f77791a6b3f9db4db99762c03aeabd221e47eb880f4a832c590b1a092
    name: Generate next CI release tag
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ secrets.CI_BOT_TOKEN }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Generate and push the tag
        run: |
          git config --global user.name "CI [bot]"
          git config --global user.email "ci-bot@git.zarantonello.dev"

          DATE=$(date -u +'%Y.%m.%d')
          PREV_TAG=$(git tag -l "ci-v${DATE}.*" | sort -V | tail -n1)

          if [ -z "$PREV_TAG" ]; then
            REVISION=1
          else
            REVISION=$(( ${PREV_TAG##*.} + 1 ))
          fi

          NEW_TAG="ci-v${DATE}.${REVISION}"

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

name: release-ci.yaml

"on":
  push:
    branches:
      - main
    paths:
      - ci.Dockerfile
  workflow_dispatch: {}
