concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  release:
    container:
      image: git.zarantonello.dev/infra/ci-semantic-release:latest@sha256:4e20d9c9b7842e0e300037ad86a3bbc4221a75d9e4beb09f24d4d3065941d47d
    name: Generate next relase tag
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ secrets.SEMANTIC_RELEASE_TOKEN }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - env:
          GIT_AUTHOR_EMAIL: semantic-release@zarantonello.dev
          GIT_AUTHOR_NAME: Semantic Release [bot]
          GIT_COMMITTER_EMAIL: semantic-release@zarantonello.dev
          GIT_COMMITTER_NAME: Semantic Release [bot]
        name: Run semantic-release
        run: semantic-release

name: release.yaml

"on":
  push:
    branches:
      - main
