concurrency:
  # Pushing a new release on main would cancel the job that pushed it.
  cancel-in-progress: false
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  release:
    container:
      image: git.zarantonello.dev/infra/ci-semantic-release:v1.0.3@sha256:d2f54e0f77791a6b3f9db4db99762c03aeabd221e47eb880f4a832c590b1a092
    name: Generate next release tag
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ secrets.CI_BOT_TOKEN }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - env:
          FORGEJO_API_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          GIT_AUTHOR_EMAIL: ci-bot@git.zarantonello.dev
          GIT_AUTHOR_NAME: CI [bot]
          GIT_COMMITTER_EMAIL: ci-bot@git.zarantonello.dev
          GIT_COMMITTER_NAME: CI [bot]
        name: Run semantic-release
        run: semantic-release

name: release.yaml

"on":
  push:
    branches:
      - main
