services:
  workspace:
    entrypoint:
      - sleep
      - infinity
    image: git.zarantonello.dev/infra/ci:v3.1.1@sha256:bed84d93be3c16150c71aab07849ac5bdc9626885b36ed612cd4b746c2965aab
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:z,cached
    working_dir: /workspace
