services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/university/notes-ci:v2026.09.09.1@sha256:6ad161c1d3b04912e8c9645fbcbb5d2253af2f1f3d1f4af60c4161e183392c05
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
