services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/university/notes:ci@sha256:3cd5fcc80e813393ab26114b9bc001dc09e65ba84b61eab9a1b53e25d90921f1
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
