services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/university/notes:ci@sha256:488c24248172b3b65b19a8ab7ca821ea490f076f3316fafc4d3624c6c2c95b93
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:z,cached
      - pnpm-cache:/usr/local/pnpm/store
    working_dir: /workspace

volumes:
  pnpm-cache: {}
