apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: notes
      apps.zarantonello.dev/namespace: university-notes
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: notes
        apps.zarantonello.dev/namespace: university-notes
    spec:
      containers:
        - image: git.zarantonello.dev/university/notes:v2.26.3@sha256:60304692ce47818a7ced05d18d960974210308f4cb85712549dc4247699ca58d
          name: notes
          ports:
            - containerPort: 80
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-hetz-nbg-0
      securityContext:
        runAsGroup: 15487
        runAsNonRoot: true
        runAsUser: 15487
        seccompProfile:
          type: RuntimeDefault
