apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: notes
      apps.zarantonello.dev/namespace: university-notes
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: notes
        apps.zarantonello.dev/namespace: university-notes
    spec:
      containers:
        - image: git.zarantonello.dev/university/notes:v2.25.6@sha256:3fc3a9609e06498a5b13c3302e415827669dd401b555254e9450f04ee15d5df5
          name: notes
          ports:
            - containerPort: 80
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-hetz-nbg-0
      securityContext:
        runAsGroup: 15487
        runAsNonRoot: true
        runAsUser: 15487
        seccompProfile:
          type: RuntimeDefault
