apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: notes
      apps.zarantonello.dev/namespace: university-notes
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: notes
        apps.zarantonello.dev/namespace: university-notes
    spec:
      containers:
        - image: git.zarantonello.dev/university/notes:v3.11.2@sha256:c4ed374f1f9e4c66f964f3ae49b7fe0bdb6164d9eecf53f2713159191f7bd53e
          name: notes
          ports:
            - containerPort: 80
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-hetz-nbg-0
      securityContext:
        runAsGroup: 15487
        runAsNonRoot: true
        runAsUser: 15487
        seccompProfile:
          type: RuntimeDefault
